# Generated by Django 3.1.6 on 2021-05-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idcom', models.AutoField(db_column='idCom', primary_key=True, serialize=False)),
                ('fechacom', models.DateField(db_column='fechaCom')),
                ('horacom', models.TimeField(db_column='horaCom')),
                ('totalcom', models.FloatField(db_column='totalCom')),
            ],
            options={
                'db_table': 'compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallesCompras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreprod', models.CharField(db_column='nombreProd', max_length=20)),
                ('precioprod', models.FloatField(db_column='precioProd')),
                ('cantidadcom', models.IntegerField(db_column='cantidadCom')),
                ('subtotalcom', models.FloatField(db_column='subTotalCom')),
            ],
            options={
                'db_table': 'detalles_compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermanenciaDetallada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horaentrada', models.TimeField(db_column='horaEntrada')),
                ('horasalida', models.TimeField(db_column='horaSalida')),
            ],
            options={
                'db_table': 'permanencia_detallada',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Compras',
        ),
        migrations.DeleteModel(
            name='DetallesCompra',
        ),
    ]
